[build]
builder = "nixpacks"

[deploy]
startCommand = "gunicorn twitter.wsgi --workers 2 --bind 0.0.0.0:$PORT --log-file -"
healthcheckPath = "/api/accounts/login_status/"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
