[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements-docker.txt"

[deploy]
startCommand = "./start.sh"
healthcheckPath = "/api/accounts/login_status/"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
