# Generated by Django 3.1.3 on 2022-03-28 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220308_2349'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
